[package]
name = "OwnIhrz-ClusterManager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0", features = ["json"]}
serde = "1.0.195"
serde_urlencoded = "0.7.1"


