cluster:
  id: 0
  max_container: 10
  port: 3450

api:
  apiToken: "api token of iHorizon"
  clientID: "bot's ID of The bot"

container:
  githubRepo: ""
  branchName: ""

database:
  host: ""
  port: ""
  database: ""
  username: ""
  password: ""